development:
  bucket: cafebop_development
  access_key_id: <%=ENV['AMAZON_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AMAZON_SECRET_ACCESS_KEY']%>

test:
  bucket: cafebop_test
  access_key_id: <%=ENV['AMAZON_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AMAZON_SECRET_ACCESS_KEY']%>

staging:
  bucket: cafebop_staging
  access_key_id: <%=ENV['AMAZON_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AMAZON_SECRET_ACCESS_KEY']%>

production:
  bucket: <%=ENV['APP_NAME'].sub(/-/, '_')%> #cafebop
  access_key_id: <%=ENV['AMAZON_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AMAZON_SECRET_ACCESS_KEY']%>
